# Generated by Django 4.2.7 on 2023-11-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rede_social', '0002_alter_comentario_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
