# Generated by Django 4.2.7 on 2023-11-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rede_social', '0003_alter_comentario_data_publicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data_publicacao',
            new_name='data_comentario',
        ),
    ]
